default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  pool: 5

development:
  <<: *default
  database: ffxiv_tasklist_development
  password: password

test:
  <<: *default
  database: ffxiv_tasklist_test
  password: password
