version: "3.8"
services:
  db:
    image: postgres:13.3
    environment:
      - POSTGRES_PASSWORD=password
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    command: yarn start
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    environment:
      - HOST=0.0.0.0
volumes:
  bundle:
