require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Rails:
  Enabled: true
  
AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'lib/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Exclude:
    - 'db/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 20

Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - development
    - test

Style/Documentation:
  Enabled: false
